package com.k3mobile.testk3.ui

import android.app.Application
import android.speech.tts.TextToSpeech
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.k3mobile.testk3.data.AppDatabase
import com.k3mobile.testk3.data.TextEntity
import com.k3mobile.testk3.data.SessionEntity
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.util.Locale


/**
 * MainViewModel
 *
 * This ViewModel handles:
 * - TextToSpeech initialization and lifecycle
 * - Access to the Room database
 * - Business logic for texts and typing sessions
 *
 * It survives configuration changes and is independent from the UI layer.
 */
class MainViewModel(application: Application) : AndroidViewModel(application), TextToSpeech.OnInitListener {
    // Data Access Object for database operations
    private val dao = AppDatabase.getDatabase(application, viewModelScope).typingDao()

    // TextToSpeech engine instance
    private var tts: TextToSpeech? = null
    // Indicates whether the TTS engine is ready to be used
    private var isTtsReady = false


    /**
     * Initializes the TextToSpeech engine when the ViewModel is created.
     * The ViewModel lifecycle ensures that the TTS engine is not recreated
     * on every UI recomposition.
     */
    init {
        tts = TextToSpeech(application, this)
    }


    /**
     * Callback triggered when the TextToSpeech engine is initialized.
     * Sets the speech rate and configures the language.
     */
    override fun onInit(status: Int) {
        // Slower speech rate for better learning and clarity
        tts?.setSpeechRate(0.65f)
        if (status == TextToSpeech.SUCCESS) {
            // Configure the TTS language to French
            val result = tts?.setLanguage(Locale.FRENCH)
            // Check that the language is supported and available
            if (result != TextToSpeech.LANG_MISSING_DATA && result != TextToSpeech.LANG_NOT_SUPPORTED) {
                isTtsReady = true
            }
        }
    }


    /**
     * Speaks the given text using TextToSpeech.
     *
     * Punctuation is explicitly announced to support typing learning,
     * which is essential in a typing training application.
     */
    fun speak(text: String) {
        if (isTtsReady) {

            // Replace punctuation symbols with spoken equivalents
            // to help users anticipate what they need to type
            val textToSpeak = text
                .replace(".", " point ")
                .replace(",", " virgule ")
                .replace("!", " point d'exclamation ")
                .replace("?", " point d'interrogation ")
                .replace(";", " point virgule ")
                .replace(":", " deux points ")

            // Send the prepared text to the TTS engine
            tts?.speak(textToSpeak, TextToSpeech.QUEUE_FLUSH, null, "UtteranceID")
        }
    }

    /**
     * Called when the ViewModel is destroyed.
     * Properly releases TextToSpeech resources to avoid memory leaks.
     */
    override fun onCleared() {
        tts?.stop()
        tts?.shutdown()
        super.onCleared()
    }

    // -------------------------
    // State management (texts)
    // -------------------------

    // Internal mutable flow for texts
    private val _texts = MutableStateFlow<List<TextEntity>>(emptyList())
    // Public immutable flow observed by the UI
    val texts = _texts.asStateFlow()

    // -------------------------
    // State management (sessions)
    // -------------------------

    // Internal mutable flow for typing sessions
    private val _sessions = MutableStateFlow<List<SessionEntity>>(emptyList())

    // Public immutable flow observed by the UI
    val sessions = _sessions.asStateFlow()

    /**
     * Loads texts from the database based on the selected category.
     */
    fun loadTextsByCategory(category: String) {
        viewModelScope.launch {
            _texts.value = dao.getTextsByCategory(category)
        }
    }


    /**
     * Loads all recorded typing sessions from the database.
     */
    fun loadStats() {
        viewModelScope.launch {
            _sessions.value = dao.getAllSessions()
        }
    }

    /**
     * Inserts a custom text created by the user into the database.
     */
    fun addCustomText(title: String, content: String) {
        viewModelScope.launch {
            val newText = TextEntity(
                idText = 0, // Auto-generated by Room
                title = title,
                content = content,
                language = "fr",
                category = "textes personnalisées",
                difficulty = 1
            )
            dao.insertText(newText)
            // Reload the custom texts category if needed
            loadTextsByCategory("textes personnalisées")
        }
    }


    /**
     * Saves a typing session with duration, speed and accuracy.
     */
    fun saveSession(textId: Long, durationMillis: Long, wpm: Double, accuracy: Double) {
        viewModelScope.launch {
            val session = SessionEntity(
                textId = textId,
                duration = durationMillis,
                wpm = wpm,
                accuracy = accuracy,
                timeStamp = System.currentTimeMillis()
            )
            dao.insertSession(session)
        }
    }

    /**
     * Arrête immédiatement toute lecture en cours.
     */
    fun stopSpeaking() {
        if (isTtsReady) {
            tts?.stop()
        }
    }
}