package com.k3mobile.testk3.data

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey


/**
 * SessionEntity
 *
 * Represents a typing practice session.
 * Each session is linked to a specific text and stores
 * performance metrics such as speed and accuracy.
 */
@Entity(
    tableName = "session_table",
    foreignKeys = [ForeignKey(
        // Parent entity representing the typed text
        entity = TextEntity::class,
        // Primary key of the parent table
        parentColumns = ["idText"],
        // Foreign key column in this table
        childColumns = ["textId"],
        // Automatically delete sessions when the related text is deleted
        onDelete = ForeignKey.CASCADE
    )]
)
data class SessionEntity(
    // Unique identifier for the session (auto-generated by Room)
    @PrimaryKey(autoGenerate = true) val idSession: Long = 0,
    // Identifier of the text associated with this typing session
    val textId: Long,
    // Timestamp indicating when the session was completed
    val timeStamp: Long = System.currentTimeMillis(),
    // Total duration of the session in milliseconds
    val duration: Long,
    // Typing speed measured in words per minute (WPM)
    val wpm: Double,
    // Typing accuracy percentage
    val accuracy: Double
)