package com.k3mobile.testk3.data

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * TextEntity
 *
 * Represents a text used for typing practice.
 * Each text belongs to a category and has a difficulty level.
 * It is read aloud using TextToSpeech and typed by the user.
 */
@Entity(tableName = "texts")
data class TextEntity(
    // Unique identifier for the text (auto-generated by Room)
    @PrimaryKey(autoGenerate = true) val idText: Long = 0,
    // Title displayed in the text selection list
    val title: String,
    // Full content of the text used for typing and TTS
    val content: String,
    // Language of the text (e.g. "fr" for French)
    val language: String,
    // Category of the text (phrases, stories, or custom texts)
    val category: String,
    // Difficulty level of the text (from 1 = easy to 5 = hard)
    val difficulty: Int
)